# Checkers Final Term Project Makefile
# Environment Varibles
#ToDO: Create a conditional to check for dependecies.
.PHONY: up
prep :
	#sudo apt install python3-pyqt4 python3 python3-pyqt5
up : prep 
	python3 start.py
