# ChessGame Using PyGame Makefile
# Environment Varibles
#ToDO: Create a conditional to check for dependecies.
.PHONY: up
prep :
	echo 'Installing Python3 and Pygame'
	sudo apt install python3-pip python3
	pip3 install pygame

up : prep 
	python3 start.py
