# ChessGame Using PyGame Makefile
# Environment Varibles

.PHONY: up

prep :
	echo 'Installing Python3 and Pygame'
	sudo apt install python3-pip python3
	pip3 install pygame

up : prep 
	python3 start.py
